#!/bin/bash
num=5
if [ $# == 0 ] 
#as same as if [ $1 = "" ]
then
	echo  "USAGE: $0 num-of-files"  >&2 #redirect to error doc 
	exit 1

elif [ $1 -lt 5 ] && [ $1 -gt 0 ]
then
	echo "Setting the default number to $num" >&2

elif [ $1 -gt 5 ] 
then
	num=$1
fi

for a in $(seq 1 $num)
do
	echo "The file$a.txt was created $(date)" > file$a.txt
done
 
